import Link from "next/link";
import { BrandLogo } from "@/components/brand-logo";
import { plans, type PlanDefinition } from "@/lib/plans";

const features = [
  ["↓", "Inbound workspace", "Create expected shipments and compare expected, received and damaged quantities."],
  ["▦", "Inventory visibility", "View usable received stock by customer, product and warehouse."],
  ["□", "Customers & products", "Maintain SKU, ASIN, FNSKU, barcode, dimensions, weight and prep instructions."],
  ["⇧", "Spreadsheet imports", "Import up to 500 products from Excel-compatible CSV or TSV files with visual column mapping."],
  ["⌁", "Barcode scanner tools", "Connect keyboard-wedge scanners and verify SKU, UPC, EAN, ASIN or FNSKU."],
  ["!", "Control Tower", "Surface deterministic shortages, overages, damage and stalled receipts in a prioritized inbox."],
  ["$", "Revenue Protection", "Set customer service rates, find unpriced operational work and turn it into invoice-ready revenue."],
  ["✓", "Prep & outbound views", "Keep prep instructions visible and identify received inventory ready for the next workflow."],
  ["◉", "Client portal preview", "Preview a customer-scoped view of products, recent inbound activity and received inventory."],
  ["?", "Guided support", "Open common workflow answers and pre-filled email support requests from every authenticated screen."],
];

export default function HomePage() {
  return <main className="min-h-screen bg-[#f5f7fa] text-[#111827]">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#162033]/95 text-white shadow-sm backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-6"><Link href="/" aria-label="FulfillOS home"><BrandLogo inverse /></Link><nav className="hidden items-center gap-6 text-sm font-semibold md:flex"><a href="#features" className="text-slate-200 hover:text-white">Features</a><a href="#about" className="text-slate-200 hover:text-white">About</a><a href="#pricing" className="text-slate-200 hover:text-white">Pricing</a><Link href="/auth/login" className="rounded-lg border border-slate-500 px-4 py-2 hover:border-white hover:bg-white/10">Sign in</Link><Link href="/auth/sign-up?plan=growth" className="rounded-lg bg-[#f59e0b] px-5 py-2 font-bold text-[#162033] hover:bg-[#fdba2d]">Start free</Link></nav><Link href="/auth/sign-up?plan=starter" className="rounded-lg bg-[#f59e0b] px-4 py-2 text-sm font-bold text-[#162033] md:hidden">Start free</Link></div></header>

    <section className="relative overflow-hidden bg-[#162033] text-white"><div className="absolute inset-0 opacity-20"><div className="absolute -left-20 top-20 h-72 w-72 rounded-full bg-[#f59e0b] blur-3xl"/><div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-blue-500 blur-3xl"/></div><div className="relative mx-auto grid min-h-[680px] max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="inline-flex rounded-full border border-[#f59e0b]/40 bg-[#f59e0b]/10 px-4 py-2 text-sm font-semibold text-[#fdba2d]">Built for prep centers and small 3PLs</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">Every unit accounted for.<span className="block text-[#f59e0b]">Every exception surfaced.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">FulfillOS brings customers, products, inbound, inventory, prep visibility, scanners and operational exceptions into one secure workspace.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/auth/sign-up?plan=growth" className="rounded-xl bg-[#f59e0b] px-7 py-4 font-bold text-[#162033] shadow-lg hover:-translate-y-0.5 hover:bg-[#fdba2d]">Create your workspace</Link><a href="#pricing" className="rounded-xl border border-slate-500 px-7 py-4 font-semibold hover:border-white hover:bg-white/10">View plans</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-300"><span>✓ Secure organization workspaces</span><span>✓ English and Spanish navigation</span><span>✓ Mobile-ready workflows</span></div></div><ProductPreview /></div></section>

    <section id="features" className="border-b border-slate-200 bg-white py-24"><div className="mx-auto max-w-7xl px-6"><SectionIntro eyebrow="Available today" title="Real operational tools—not a roadmap disguised as a feature list" description="Every capability below is already present in FulfillOS. Customer service rates and Revenue Protection are active today. Invoicing, external client invitations and AI-assisted decisions are not advertised until their secure workflows are complete."/><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([icon,title,description])=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-amber-300 hover:shadow-lg"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#162033] text-xl font-black text-[#f59e0b]">{icon}</span><h3 className="mt-5 text-xl font-black text-[#162033]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>

    <section id="about" className="bg-[#f5f7fa] py-24"><div className="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionIntro eyebrow="Why FulfillOS" title="A clearer operating system for the warehouse" description="Traditional systems make operators hunt across modules. FulfillOS is built around the question that matters each morning: what needs attention now?"/><div className="mt-8 space-y-4"><Benefit title="Tenant-aware by design" text="Customers, warehouses and records remain scoped to the authenticated organization."/><Benefit title="Rules before AI" text="Shortages, overages, damage, delays and uncaptured pricing are calculated deterministically."/><Benefit title="Floor-friendly" text="Responsive pages, large actions and keyboard-wedge scanner support reduce typing."/><Benefit title="Defensible operational history" text="Physical Proof of Work remains linked to operations while software changes remain in an immutable Audit Trail."/></div></div><div className="grid gap-4 sm:grid-cols-2"><ValueCard label="Control Tower" value="Prioritized" text="Exceptions ranked by severity and affected units."/><ValueCard label="Revenue Protection" value="Traceable" text="Customer rates price captured operational work without changing inventory."/><ValueCard label="Catalog onboarding" value="500 rows" text="Per mapped CSV/TSV product import."/><ValueCard label="Workspace access" value="2 languages" text="English and Spanish authenticated navigation."/></div></div></section>

    <section id="pricing" className="bg-white py-24"><div className="mx-auto max-w-7xl px-6"><SectionIntro eyebrow="Simple monthly pricing" title="Choose the operating capacity that fits today" description="Floor scans are not billed individually. Plans scale by warehouses, customers and understandable monthly operating volume."/><div className="mt-10 rounded-3xl bg-[#162033] p-6 text-white shadow-xl sm:flex sm:items-center sm:justify-between sm:gap-8 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#fdba2d]">30-Day FulfillOS Control Trial</p><h3 className="mt-2 text-2xl font-black">Try Control capabilities without choosing a paid plan first.</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">No credit card. Need more time for a real evaluation? Request a 14-day extension. Enterprise operations can request a guided 30–60 day pilot.</p></div><Link href="/auth/sign-up" className="mt-5 inline-flex min-h-12 shrink-0 items-center justify-center rounded-xl bg-[#f59e0b] px-6 font-bold text-[#162033] sm:mt-0">Start free trial</Link></div><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan)=><PricingCard key={plan.id} plan={plan}/>)}</div><div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm leading-6 text-slate-600"><strong className="text-[#162033]">Plan entitlements:</strong> these warehouse, customer and volume limits define each paid tier. Server-enforced subscription limits will activate with the Supabase billing configuration. No charge is calculated per barcode scan.</div></div></section>

    <section className="bg-[#243247] py-20 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-6 lg:flex-row lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#fdba2d]">Start with the right plan</p><h2 className="mt-3 text-4xl font-black">Move the operation out of disconnected spreadsheets.</h2><p className="mt-4 max-w-2xl text-slate-300">Choose a plan, create your secure workspace and begin with customers, products and warehouse setup.</p></div><Link href="/auth/sign-up?plan=growth" className="rounded-xl bg-[#f59e0b] px-7 py-4 font-bold text-[#162033] hover:bg-[#fdba2d]">Start with Growth · $299/mo</Link></div></section>
    <footer className="bg-[#162033] text-slate-300"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-6 py-8 sm:flex-row"><p>© 2026 FulfillOS. All rights reserved.</p><p>Receive. Prep. Store. Ship. Resolve.</p></div></footer>
  </main>;
}

function ProductPreview(){return <div className="rounded-3xl border border-white/10 bg-[#243247] p-4 shadow-2xl"><div className="rounded-2xl bg-[#f5f7fa] p-5 text-[#111827]"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><div><p className="text-sm text-slate-500">Control Tower preview</p><h2 className="text-xl font-black text-[#162033]">Needs attention</h2></div><span className="rounded-lg bg-amber-100 px-3 py-2 text-xs font-bold text-amber-800">Rules active</span></div><div className="mt-5 space-y-3"><PreviewIssue severity="HIGH" title="Inbound shortage" detail="Expected quantity does not match completed receipt."/><PreviewIssue severity="MEDIUM" title="Damaged inventory" detail="Received units include recorded damage."/><PreviewIssue severity="MEDIUM" title="Stalled receipt" detail="Inbound exceeded the operating-time threshold."/></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#162033] p-4 text-white"><p className="text-xs uppercase text-slate-400">Products</p><p className="mt-2 font-bold">Mapped imports</p></div><div className="rounded-xl bg-[#162033] p-4 text-white"><p className="text-xs uppercase text-slate-400">Floor tools</p><p className="mt-2 font-bold">Barcode lookup</p></div></div></div></div>}
function PreviewIssue({severity,title,detail}:{severity:string;title:string;detail:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><p className="font-bold text-[#162033]">{title}</p><span className="rounded-full bg-orange-100 px-2 py-1 text-[10px] font-black text-orange-800">{severity}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>}
function SectionIntro({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#c7511f]">{eyebrow}</p><h2 className="mt-4 text-4xl font-black tracking-tight text-[#162033] sm:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-slate-600">{description}</p></div>}
function Benefit({title,text}:{title:string;text:string}){return <div className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#067d62] text-sm font-bold text-white">✓</span><div><p className="font-bold text-[#162033]">{title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div></div>}
function ValueCard({label,value,text}:{label:string;value:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-[#c7511f]">{label}</p><p className="mt-3 text-3xl font-black text-[#162033]">{value}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>}
function PricingCard({plan}:{plan:PlanDefinition}){return <article className={`relative flex flex-col rounded-3xl border p-6 ${plan.highlighted?"border-[#f59e0b] bg-[#162033] text-white shadow-xl":"border-slate-200 bg-white text-[#162033] shadow-sm"}`}>{plan.highlighted&&<span className="absolute -top-3 left-6 rounded-full bg-[#f59e0b] px-3 py-1 text-xs font-black uppercase text-[#162033]">Most popular</span>}<h3 className="text-2xl font-black">{plan.name}</h3><p className={`mt-3 min-h-16 text-sm leading-6 ${plan.highlighted?"text-slate-300":"text-slate-600"}`}>{plan.promise}</p><p className="mt-5"><span className="text-4xl font-black">${plan.price}</span><span className={plan.highlighted?"text-slate-400":"text-slate-500"}>/month</span></p><dl className={`mt-5 space-y-2 border-y py-4 text-sm ${plan.highlighted?"border-white/10":"border-slate-200"}`}><Limit label="Warehouses" value={plan.warehouses===null?"Unlimited":String(plan.warehouses)}/><Limit label="Customers" value={plan.customers===null?"Unlimited":String(plan.customers)}/><Limit label="Monthly operations" value={plan.monthlyOperations===null?"Custom":plan.monthlyOperations.toLocaleString("en-US")}/></dl><ul className="mt-5 flex-1 space-y-3 text-sm">{plan.features.map((feature)=><li key={feature} className="flex gap-2"><span className="font-bold text-[#f59e0b]">✓</span><span>{feature}</span></li>)}</ul><Link href={`/auth/sign-up?plan=${plan.id}`} className={`mt-7 inline-flex min-h-12 items-center justify-center rounded-xl px-5 text-center font-bold ${plan.highlighted?"bg-[#f59e0b] text-[#162033] hover:bg-[#fdba2d]":"bg-[#162033] text-white hover:bg-[#243247]"}`}>Start Control trial</Link><p className={`mt-2 text-center text-xs ${plan.highlighted?"text-slate-400":"text-slate-500"}`}>{plan.name} preference saved for later</p></article>}
function Limit({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><dt>{label}</dt><dd className="font-bold">{value}</dd></div>}
