"use client";

import { useEffect, useRef, useState } from "react";

type Lookup = { found: boolean; product?: { id: string; sku: string; title: string; barcode: string | null; asin: string | null; fnsku: string | null; customer: string } };

export function ScannerSetup() {
  const [name, setName] = useState(""); const [code, setCode] = useState(""); const [status, setStatus] = useState<"idle" | "searching" | "found" | "missing">("idle"); const [product, setProduct] = useState<Lookup["product"]>(); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { setName(localStorage.getItem("fulfillos-scanner-name") ?? "Warehouse scanner"); input.current?.focus(); }, []);
  async function scan(value: string) { const normalized = value.trim(); if (!normalized) return; setStatus("searching"); const response = await fetch(`/api/products/lookup?code=${encodeURIComponent(normalized)}`); const result = await response.json() as Lookup; setProduct(result.product); setStatus(result.found ? "found" : "missing"); setCode(""); input.current?.focus(); }
  return <div className="mt-8 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-[#c7511f]">Connection profile</p><label className="mt-5 block text-sm font-bold text-[#162033]">Scanner name<input value={name} onChange={(event) => setName(event.target.value)} onBlur={() => localStorage.setItem("fulfillos-scanner-name", name)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4" /></label><ol className="mt-6 space-y-4 text-sm leading-6 text-slate-600"><li><strong className="text-[#162033]">1.</strong> Pair the scanner by USB or Bluetooth.</li><li><strong className="text-[#162033]">2.</strong> Configure it to send an Enter/Return suffix.</li><li><strong className="text-[#162033]">3.</strong> Click the scan field and scan a known SKU, UPC, EAN, FNSKU or ASIN.</li></ol><div className="mt-6 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Compatible with keyboard-wedge scanners, including common Zebra, Socket Mobile, Honeywell and generic USB models. Hardware pairing remains managed by the device operating system.</div></section>
    <section className="rounded-3xl bg-[#162033] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#fdba2d]">Live test · {name}</p><h2 className="mt-2 text-2xl font-black">Scan a product</h2><form onSubmit={(event) => { event.preventDefault(); void scan(code); }}><input ref={input} value={code} onChange={(event) => setCode(event.target.value)} placeholder="Scanner input appears here" autoComplete="off" className="mt-6 min-h-16 w-full rounded-2xl border-2 border-[#f59e0b] bg-white px-5 font-mono text-xl text-[#162033] outline-none" /></form><div aria-live="polite" className="mt-5 min-h-36 rounded-2xl bg-white/10 p-5">{status === "idle" && <p className="text-slate-300">Waiting for a scan…</p>}{status === "searching" && <p>Searching catalog…</p>}{status === "missing" && <><p className="font-bold text-amber-300">No matching product</p><p className="mt-2 text-sm text-slate-300">Check the barcode value or import the product first.</p></>}{status === "found" && product && <><p className="font-black text-emerald-300">✓ Product verified</p><h3 className="mt-3 text-xl font-bold">{product.title}</h3><p className="mt-1 font-mono text-sm text-slate-300">SKU {product.sku}</p><p className="mt-1 text-sm text-slate-300">{product.customer}</p></>}</div></section>
  </div>;
}
